services:
  postgres:
    container_name: domo-postgres
    image: postgres:14-alpine
    ports:
      - ${DATABASE_PORT_FORWARD}:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: unless-stopped
    networks:
      - domo-network

volumes:
  postgres_data:
  
networks:
  domo-network:
    driver: bridge